### ISSUE TITLE
How to install? Is there any way to install it on Windows 7 machine?

### ISSUE THREAD

**Issue by wolskiru** [ArztSamuel/Applying_EANNs#2]
How to install? Is there any way to install it on Windows 7 machine?
Requirements?

**Comment by ArztSamuel** [comment]
This project is a Unity Project.
In order to run it, you simply have to execute the `Applying EANNs.exe` located in the [Build](https://github.com/ArztSamuel/Applying_EANNs/tree/master/Build) folder.

If you are running on Windows, you should already meet all software-related requirements.

If you want to tinker with the project's settings or try different maps you have to download Unity (the game-engine this project was developed with). I recommend using Unity 5.5.2 for opening the project, in order to avoid any compatibility problems with newer Unity versions. You can find an archive of all Unity versions [here](https://unity3d.com/get-unity/download/archive).

If you encounter any issues getting the build to run, feel free to comment on this issue.
