### ISSUE TITLE
How can i get the most recent adjusted weights values after closing the application?

### ISSUE THREAD

**Issue by dan62** [ArztSamuel/Applying_EANNs#3]
Hey there id like to get the most recent weights values after closing the simulation and save these to a text file so i can use them on the next time i open the simulation. Could you assist me with this? great repository by the way!

**Comment by ArztSamuel** [comment]
Hi, thanks for the kind words!
There is already a mechanism for saving the weight sets of the first `N` cars who manage to finish the course (see Main scene -> EvolutionManager Object -> "Save First N Genotypes" in Inspector).
If you want to save the weights of a specific Genotype (i.e. car) you can have a look at how I implemented that in the `EvolutionManager` class (see method `CheckForTrackFinished` in `EvolutionManager.cs`, where I save the first `N` genotypes who finished the track).

For short: the `Genotype` class incorporates all current weight values of a specific car. This class also implements a `SaveToFile` and `LoadFromFile` method.
If I remember correctly, I only implemented the `LoadFromFile` method for completeness sake and ended up never using it. So if you encounter any bugs with that one, please let me know and I will have another look at it ;)

**Comment by Hiro1307** [comment]
Hello, I've already manage to have the save file of fitness value which in the unity you have change it to "Eval" I presume. But I can't seem to find the LoadFromFile method inside the EvolutionManager.cs,

**Comment by ArztSamuel** [comment]
The `Genotype` class holds all current weight values and also implements the `SaveToFile` (see https://github.com/ArztSamuel/Applying_EANNs/blob/master/UnityProject/Assets/Scripts/AI/Evolution/Genotype.cs#L139) and `LoadFromFile` (see https://github.com/ArztSamuel/Applying_EANNs/blob/master/UnityProject/Assets/Scripts/AI/Evolution/Genotype.cs#L174) methods.

In order to use them, simply call the `SaveToFile` method on a Genotype you would like to save and then call `LoadFromFile` with the correct file path once you want to load the Genotype again. This method will return the loaded Genotype.
