### ISSUE TITLE
Change NN size

### ISSUE THREAD

**Issue by simonbogh** [ArztSamuel/Applying_EANNs#4]
Hi,

Nice project!

I was wondering, where do you set the size of the neural network?

**Comment by ArztSamuel** [comment]
Hi,

Thanks for the kind words!

That's a good question. The hidden layers can be adjusted quite simply via the unity editor:
Inside the `Main` scene there is a `EvolutionManager`. When selected you can find a dropdown on the Component in the Inspector called `FNN Topology`, where you can set the amount of layers (`Size`), and the amount of neurons of each layer (`Element X`). The inspector is simply default drawing a serialized array, hence the weird labels.

The input and output layers (i.e. the first and last element) need to be handled a bit differently. You can also change them right there in the inspector, however, you will probably also have to change some parts of the code, since the amount of input neurons also needs to match the amount of sensors on the car. Similarly only the two outputs are currently used in code, so defining another one would not have any effect (other than probably slowing down training).

**Comment by simonbogh** [comment]
Found it, thanks for the explanation. 

I decided to hide the neural network panel as with bigger networks the simulation got a bit slow. Besides that, it works quite nicely, I am building it directly for Mac with the latest Unity version 2019.12f1.

**Comment by ArztSamuel** [comment]
Great, I'm glad it also works with the newest versions.

I have to admit that I haven't touched the project since 5.6 😅

I am always interested in other applications that arise from this project, so feel free to keep me updated or to let me know if you have any other questions.

**Comment by simonbogh** [comment]
Same here, always many new exciting things to try out 😊

Thanks for the project again, will play around with it a bit.
