### ISSUE TITLE
Implement map changing during training

### ISSUE THREAD

**Issue by AlexGatz** [ArztSamuel/Applying_EANNs#5]
You are most familiar with your code. Can you see a strait forward way to change the map at certain intervals or perhaps after a certain goal is achieved to perhaps train the model to become more adaptive. Perhaps this already occurs, or does the model just learn to succeed at one specific map at a time?

Thank you! Excellent work.

**Comment by ArztSamuel** [comment]
Hi!
Changing the environment in specific intervals in order to train a more generalized model is a great idea. This is not currently implemented in the project, you can only select the map to train on, by changing the corresponding inspector field in the main scene.

Implementing this would require some changes to the codebase. I've had a quick look at the project again just now, and I think there might be a quite easy way to achieve it though:

You might be able to get away with simply unloading the current track scene and additively loading the other track. I haven't tried that yet and you might need to have to do some slight adaptations, but since the EvolutionManager and GameStateManager as well as the spawned cars are located in their own scene (Main) this should work. You might have to be careful at which time of the evolutionary cycle you perform this scene switch though and you will probably have to make sure the scene is fully loaded before continuing with the simulation.

I hope that helps! Thanks for the kind words!

Let me know if that worked out for you, or if you got any more questions!

**Comment by AlexGatz** [comment]
Wow, thank you so much for the response! I will try to make some progress on this, thank you for the direction.
