### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [ArztSamuel/Applying_EANNs#6]
If I train the cars in one track and then use those cars on a new track, will they be able to succeed in first attempt or they have to relearn the new track ?

**Comment by ArztSamuel** [comment]
Hi, depends on the new track.
As long as the new track doesn't introduce any fundamentally new concepts (such as u-turns) that weren't remotely present in the original track, they should be able to complete it. Otherwise they will need some more training in order to be able to also learn the newly introduced concepts.
